name: nearme_fn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.2.3
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^8.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/images/
